-- 1. Create profiles table if not exists
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  phone text,
  name text,
  branch text,
  college text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz
);

-- 2. Create user_activity table if not exists
create table if not exists public.user_activity (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  event text not null,
  user_agent text,
  created_at timestamptz not null default now()
);

-- 3. Create mock_attempts table if not exists
create table if not exists public.mock_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  branch text not null,
  year integer,
  score integer not null,
  correct integer not null,
  attempted integer not null,
  total integer not null,
  accuracy integer not null,
  time_spent integer,
  answers jsonb,
  report jsonb,
  created_at timestamptz not null default now()
);

-- 4. Create practice_sessions table if not exists
create table if not exists public.practice_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  branch text not null,
  year integer,
  score integer not null,
  correct integer not null,
  attempted integer not null,
  total integer not null,
  accuracy integer not null,
  time_spent integer,
  answers jsonb,
  report jsonb,
  created_at timestamptz not null default now()
);

-- 5. Create issue_reports table if not exists
create table if not exists public.issue_reports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null default auth.uid(),
  question_id text not null,
  paper_id text,
  branch text,
  year integer,
  question_no integer,
  issue_type text not null,
  notes text,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.user_activity enable row level security;
alter table public.mock_attempts enable row level security;
alter table public.practice_sessions enable row level security;
alter table public.issue_reports enable row level security;

-- Drop existing policies if they exist to prevent query failures
drop policy if exists "Users can read own profile" on public.profiles;
drop policy if exists "Users can upsert own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Users can insert own activity" on public.user_activity;
drop policy if exists "Admins can read all activity" on public.user_activity;
drop policy if exists "Users can read own mock attempts" on public.mock_attempts;
drop policy if exists "Users can insert own mock attempts" on public.mock_attempts;
drop policy if exists "Users can read own practice sessions" on public.practice_sessions;
drop policy if exists "Users can insert own practice sessions" on public.practice_sessions;
drop policy if exists "Anyone can insert issue reports" on public.issue_reports;
drop policy if exists "Admins can read all issue reports" on public.issue_reports;
drop policy if exists "Admins can update all issue reports" on public.issue_reports;
drop policy if exists "Anyone can download papers" on storage.objects;
drop policy if exists "Admins can upload papers" on storage.objects;

-- Recreate policies for profiles
create policy "Users can read own profile"
  on public.profiles for select
  using (
    auth.uid() = id
    or auth.jwt() ->> 'email' = 'pulipatirahul19@gmail.com'
    or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );

create policy "Users can upsert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Recreate policies for user_activity
create policy "Users can insert own activity"
  on public.user_activity for insert
  with check (auth.uid() = user_id);

create policy "Admins can read all activity"
  on public.user_activity for select
  using (
    auth.uid() = user_id
    or auth.jwt() ->> 'email' = 'pulipatirahul19@gmail.com'
    or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );

-- Recreate policies for mock_attempts
create policy "Users can read own mock attempts"
  on public.mock_attempts for select
  using (
    auth.uid() = user_id
    or auth.jwt() ->> 'email' = 'pulipatirahul19@gmail.com'
    or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );

create policy "Users can insert own mock attempts"
  on public.mock_attempts for insert
  with check (auth.uid() = user_id);

-- Policies for practice_sessions
create policy "Users can read own practice sessions"
  on public.practice_sessions for select
  using (
    auth.uid() = user_id
    or auth.jwt() ->> 'email' = 'pulipatirahul19@gmail.com'
    or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );

create policy "Users can insert own practice sessions"
  on public.practice_sessions for insert
  with check (auth.uid() = user_id);

-- Policies for issue_reports
create policy "Anyone can insert issue reports"
  on public.issue_reports for insert
  with check (true);

create policy "Admins can read all issue reports"
  on public.issue_reports for select
  using (
    auth.jwt() ->> 'email' = 'pulipatirahul19@gmail.com'
    or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );

create policy "Admins can update all issue reports"
  on public.issue_reports for update
  using (
    auth.jwt() ->> 'email' = 'pulipatirahul19@gmail.com'
    or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );

-- Create storage bucket for papers (if not exists)
insert into storage.buckets (id, name, public)
values ('papers', 'papers', true)
on conflict (id) do nothing;

-- Set up policies for the papers storage bucket
create policy "Anyone can download papers"
  on storage.objects for select
  using (bucket_id = 'papers');

create policy "Admins can upload papers"
  on storage.objects for insert
  with check (
    bucket_id = 'papers'
    and (
      auth.jwt() ->> 'email' = 'pulipatirahul19@gmail.com'
      or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
      or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
    )
  );

-- Indexes for performance
create index if not exists profiles_created_at_idx on public.profiles(created_at);
create index if not exists profiles_last_seen_at_idx on public.profiles(last_seen_at);
create index if not exists user_activity_created_at_idx on public.user_activity(created_at);
create index if not exists user_activity_event_idx on public.user_activity(event);
create index if not exists user_activity_user_id_idx on public.user_activity(user_id);
create index if not exists mock_attempts_user_id_idx on public.mock_attempts(user_id);
create index if not exists mock_attempts_created_at_idx on public.mock_attempts(created_at);
create index if not exists practice_sessions_user_id_idx on public.practice_sessions(user_id);
create index if not exists practice_sessions_created_at_idx on public.practice_sessions(created_at);
create index if not exists issue_reports_status_idx on public.issue_reports(status);
create index if not exists issue_reports_created_at_idx on public.issue_reports(created_at);

-- 6. Ensure questions verification column exists and configure select RLS override policies
alter table public.questions add column if not exists is_verified boolean default true;
alter table public.questions enable row level security;

drop policy if exists "Anyone can select questions" on public.questions;
drop policy if exists "Admins can select all questions" on public.questions;

create policy "Anyone can select questions"
  on public.questions for select
  using (is_verified = true);

create policy "Admins can select all questions"
  on public.questions for select
  using (
    auth.jwt() ->> 'email' = 'pulipatirahul19@gmail.com'
    or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );

