create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  phone text,
  name text,
  branch text,
  college text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz
);

create table if not exists public.user_activity (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  event text not null,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.user_activity enable row level security;

create policy "Users can read own profile"
  on public.profiles for select
  using (
    auth.uid() = id
    or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );

create policy "Users can upsert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Users can insert own activity"
  on public.user_activity for insert
  with check (auth.uid() = user_id);

create policy "Admins can read all activity"
  on public.user_activity for select
  using (
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );

create index if not exists profiles_created_at_idx on public.profiles(created_at);
create index if not exists profiles_last_seen_at_idx on public.profiles(last_seen_at);
create index if not exists user_activity_created_at_idx on public.user_activity(created_at);
create index if not exists user_activity_event_idx on public.user_activity(event);
create index if not exists user_activity_user_id_idx on public.user_activity(user_id);
